version: '3.1'

services:
  miner1:
    build: .
    image: lsapan/boocoin
    ports:
      - 9811:9811
    environment:
      - DJANGO_SETTINGS_MODULE=local_settings
    volumes:
      - .:/home/docker/code

  miner2:
    image: lsapan/boocoin
    ports:
      - 9812:9811
    environment:
      - DJANGO_SETTINGS_MODULE=local_settings2
    volumes:
      - ./local_settings2.py:/home/docker/code/local_settings2.py
      - ./db2.sqlite3:/home/docker/code/db.sqlite3
      - ./genesis.json:/home/docker/code/genesis.json
  
  miner3:
    image: lsapan/boocoin
    ports:
      - 9813:9811
    environment:
      - DJANGO_SETTINGS_MODULE=local_settings
    volumes:
      - ./local_settings3.py:/home/docker/code/local_settings.py
      - ./db3.sqlite3:/home/docker/code/db.sqlite3
      - ./genesis.json:/home/docker/code/genesis.json
