version: '3.1'

services:
  miner1:
    build: .
    image: lsapan/boocoin
    ports:
      - 9811:9811
    environment:
      - DJANGO_SETTINGS_MODULE=local_settings1
      - DB_NAME=db1.sqlite3
    volumes:
      - .:/home/docker/code
  
  miner2:
    build: .
    image: lsapan/boocoin
    ports:
      - 9812:9811
    environment:
      - DJANGO_SETTINGS_MODULE=local_settings2
      - DB_NAME=db2.sqlite3
    volumes:
      - .:/home/docker/code
  
  miner3:
    build: .
    image: lsapan/boocoin
    ports:
      - 9813:9811
    environment:
      - DJANGO_SETTINGS_MODULE=local_settings3
      - DB_NAME=db3.sqlite3
    volumes:
      - .:/home/docker/code
