version: '3.1'

services:
  miner:
    build: .
    image: lsapan/boocoin
    ports:
      - 9811:9811
    environment:
      - DJANGO_SETTINGS_MODULE=local_settings
    volumes:
      - .:/home/docker/code
