# Generated by Django 2.0.3 on 2018-04-02 09:21

import boocoin.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('depth', models.IntegerField()),
                ('miner', models.CharField(max_length=96)),
                ('balances', models.TextField()),
                ('merkle_root', models.CharField(max_length=64)),
                ('extra_data', models.BinaryField(null=True)),
                ('time', models.DateTimeField()),
                ('signature', models.CharField(max_length=96)),
                ('previous_block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='boocoin.Block')),
            ],
        ),
        migrations.CreateModel(
            name='SyncLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64)),
                ('from_account', models.CharField(db_index=True, max_length=96, null=True)),
                ('to_account', models.CharField(db_index=True, max_length=96)),
                ('coins', models.DecimalField(decimal_places=8, max_digits=20)),
                ('extra_data', models.BinaryField(null=True)),
                ('time', models.DateTimeField()),
                ('signature', models.CharField(max_length=96)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='boocoin.Block')),
            ],
            bases=(boocoin.models.TransactionHashMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UnconfirmedTransaction',
            fields=[
                ('hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('from_account', models.CharField(db_index=True, max_length=96)),
                ('to_account', models.CharField(db_index=True, max_length=96)),
                ('coins', models.DecimalField(decimal_places=8, max_digits=20)),
                ('extra_data', models.BinaryField(null=True)),
                ('time', models.DateTimeField()),
                ('signature', models.CharField(max_length=96)),
            ],
            bases=(boocoin.models.TransactionHashMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('hash', 'block')},
        ),
    ]
