# Generated by Django 2.0.3 on 2018-04-01 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('miner', models.CharField(max_length=64)),
                ('balances', models.TextField()),
                ('extra_data', models.BinaryField(null=True)),
                ('time', models.DateTimeField()),
                ('signature', models.CharField(max_length=96)),
                ('previous_block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='boocoin.Block')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('from_account', models.CharField(db_index=True, max_length=64, null=True)),
                ('to_account', models.CharField(db_index=True, max_length=64)),
                ('coins', models.DecimalField(decimal_places=8, max_digits=20)),
                ('extra_data', models.BinaryField(null=True)),
                ('time', models.DateTimeField()),
                ('signature', models.CharField(max_length=96)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='boocoin.Block')),
            ],
        ),
    ]
