# Generated by Django 2.0.3 on 2018-04-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boocoin', '0002_unconfirmedtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='unconfirmedtransaction',
            name='from_account',
            field=models.CharField(db_index=True, default='', max_length=96),
            preserve_default=False,
        ),
    ]
